-- ================================================================
-- MCC · Seed da obra CPPI (dados reais — 22 RDOs / contrato FUNEAS 116.2025)
-- Executar APÓS schema.sql. A obra CPPI não possui planilha analítica
-- (somente RDOs em %), então a EAP entra com unidade "%" e qtde 100 —
-- o avanço é registrado em pontos percentuais, como nos RDOs originais.
-- Para uma obra COM planilha analítica (ex.: Maringá), use o upload no
-- módulo Operacional → Obras, que cria a EAP em unidade física (m², m³, kg...).
-- ================================================================

with nova as (
  insert into obras (codigo, nome, contratante, contrato, local, prazo_dias, desconto, data_inicio)
  values (
    'FUN-PIR-004-REF-CPP',
    'Reforma CPPI — Piraquara',
    'Fundação Estatal de Atenção em Saúde do Paraná - FUNEAS',
    '21.344.594-4 - CONTRATO 116.2025 - SERV. REFORMA - MIRIAD - CPPI',
    'Av. São Roque, 716 - Jardim Santa Mônica, Piraquara - PR, 83302-200',
    300, 0, '2025-04-01'
  )
  returning id
)
insert into eap_itens (obra_id, codigo, descricao, unidade, qtde, valor_unit, valor_total, ambiente, ordem)
select id, t.c, t.d, t.u, t.q, t.vu, t.vt, t.amb, t.o from nova, (values
  ('5.10.1', 'CANALETA MEIA CANA PRÉ-MOLDADA DE CONCRETO (D = 20 CM) - FORNECIMENTO E INSTALAÇÃO. AF_08/', '%', 100, 1, 100, 'externo', 1),
  ('5.10.2', 'GRELHA DE CONCRETO PARA CANALETA - L=30CM - COM PASSAGEM DE VEÍCULOS', '%', 100, 1, 100, 'externo', 2),
  ('9.16', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 3),
  ('15.2', 'REMOÇÃO DE ENTULHO COM CAÇAMBA METÁLICA, INCLUSIVE CARGA MANUAL E DESCARGA EM BOTA-FORA', '%', 100, 1, 100, 'interno', 4),
  ('15.3', 'REGULARIZAÇÃO MANUAL E COMPACTAÇÃO COM PLACA VIBRATÓRIA', '%', 100, 1, 100, 'interno', 5),
  ('15.10', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM PAREDES, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 6),
  ('18.15', 'APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014', '%', 100, 1, 100, 'interno', 7),
  ('18.16', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 8),
  ('19.15', 'APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014', '%', 100, 1, 100, 'interno', 9),
  ('19.16', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 10),
  ('21.11', 'FORRO DE PVC, LISO, PARA AMBIENTES COMERCIAIS, INCLUSIVE ESTRUTURA DE FIXAÇÃO. AF_05/2017_', '%', 100, 1, 100, 'interno', 11),
  ('22.15', 'APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014', '%', 100, 1, 100, 'interno', 12),
  ('22.16', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 13),
  ('24.16', 'APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014', '%', 100, 1, 100, 'interno', 14),
  ('24.17', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 15),
  ('25.7', 'PISO VINÍLICO EM MANTA HOMOGÊNEO EM MANTA ESPESSURA 2MM - VER ESPECIFICAÇÕES', '%', 100, 1, 100, 'interno', 16),
  ('25.8', 'RODAPÉ EM ALUMÍNIO FIXADO NA PAREDE - VER ESPECIFICAÇÕES', '%', 100, 1, 100, 'interno', 17),
  ('25.12', 'APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM PAREDES, DUAS DEMÃOS. AF_06/2014', '%', 100, 1, 100, 'interno', 18),
  ('26.4', 'LASTRO COM MATERIAL GRANULAR, APLICADO EM PISOS OU LAJES SOBRE SOLO, ESPESSURA DE *5 CM*. ', '%', 100, 1, 100, 'interno', 19),
  ('26.5', 'PISO EM CONCRETO 20 MPA PREPARO MECÂNICO, ESPESSURA 7CM. AF_09/2020', '%', 100, 1, 100, 'interno', 20),
  ('26.6', 'ARGAMASSA TRAÇO 1:3 (EM VOLUME DE CIMENTO E AREIA MÉDIA ÚMIDA) COM ADIÇÃO DE IMPERMEABILIZ', '%', 100, 1, 100, 'externo', 21),
  ('26.7', 'REVESTIMENTO CERÂMICO PARA PISO COM PLACAS TIPO PORCELANATO DE DIMENSÕES 60X60 CM APLICADA', '%', 100, 1, 100, 'interno', 22),
  ('28.5', 'PORTA DE VIDRO TRANSPARENTE ABRIR 1 FOLHA', '%', 100, 1, 100, 'interno', 23),
  ('28.10', 'PORTA DE FERRO COMPACTA EM CHAPA, INCLUS. BATENTES E FERRAGENS', '%', 100, 1, 100, 'interno', 24),
  ('28.11', 'PORTA DE CORRER - TIPO MEXICANA - MADEIRA DE LEI MACIÇA', '%', 100, 1, 100, 'interno', 25),
  ('28.14', 'PORTA DE FERRO COMPACTA EM CHAPA, INCLUS. BATENTES E FERRAGENS', '%', 100, 1, 100, 'interno', 26),
  ('29.2.1', 'CAIXA DE INSPEÇÃO 80X80CM, PROFUNDIDADE=110CM, TAMPA EM CONCRETO ARMADO COM CANTONEIRAS E=', '%', 100, 1, 100, 'externo', 27),
  ('30.4', 'RACK DE PAREDE 6U, 19" 450MM - FORNEC. E INST.', '%', 100, 1, 100, 'interno', 28),
  ('33.1', 'AR CONDICIONADO SPLIT INVERTER, HI-WALL (PAREDE), 18000 BTU/H, CICLO FRIO - FORNECIMENTO E', '%', 100, 1, 100, 'interno', 29),
  ('33.2', 'UNIDADE EVAPORADORA - CONDENSADORA - TIPO HI-WALL - 18.000BTU/H', '%', 100, 1, 100, 'interno', 30),
  ('33.3', 'UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)', '%', 100, 1, 100, 'interno', 31),
  ('33.4', 'UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 171.000 BTU/H (15 TRTR)', '%', 100, 1, 100, 'interno', 32),
  ('33.5', 'KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A22T', '%', 100, 1, 100, 'interno', 33),
  ('33.7', 'KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A33T', '%', 100, 1, 100, 'interno', 34),
  ('33.12', 'FANCOLETE HOSPITALAR', '%', 100, 1, 100, 'interno', 35),
  ('33.38', 'UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)', '%', 100, 1, 100, 'interno', 36),
  ('34.1', 'CÂMARA FRIGORÍFICA PARA RESFRIADOS', '%', 100, 1, 100, 'interno', 37)
) as t(c, d, u, q, vu, vt, amb, o);

-- RDOs históricos (para calibrar a produtividade no Painel Geral)
with obra as (select id from obras where codigo = 'FUN-PIR-004-REF-CPP' limit 1)
insert into rdos (obra_id, numero, data, clima, efetivo, comentarios, atividades, equipe)
select obra.id, t.numero, t.data::date, t.clima, t.efetivo, t.comentarios, t.atividades, t.equipe
from obra, (values
  ('00350', '2026-03-16', 'NP', 4, 'Na data de hoje a equipe finalizou a instalação das canaletas e grelhas pré moldadas na passagem da circulação de equinos. A equipe de pintura deu sequência na área do Rack finalizando a pintura do teto.', '[{"eap": "5.10.1", "descricao": "CANALETA MEIA CANA PRÉ-MOLDADA DE CONCRETO (D = 20 CM) - FORNECIMENTO E INSTALAÇÃO. AF_08/", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "5.10.2", "descricao": "GRELHA DE CONCRETO PARA CANALETA - L=30CM - COM PASSAGEM DE VEÍCULOS", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "9.16", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Caio Vinícius Martins do Amaral"}]'::jsonb),
  ('00351', '2026-03-17', 'NP', 5, 'Hoje a equipe focou na àrea livre dos barracões realizando a remoção de uma área que apresentou uma fissura refazendo assim a mesma A equipe de pintura realizou a terceira demão de tinta acrílica em paredes finalizando assim as demãos necessárias', '[{"eap": "15.2", "descricao": "REMOÇÃO DE ENTULHO COM CAÇAMBA METÁLICA, INCLUSIVE CARGA MANUAL E DESCARGA EM BOTA-FORA", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "15.3", "descricao": "REGULARIZAÇÃO MANUAL E COMPACTAÇÃO COM PLACA VIBRATÓRIA", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "15.10", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM PAREDES, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Caio Vinícius Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Cauan Eduardo Martins do Amaral"}]'::jsonb),
  ('00352', '2026-03-18', 'NP', 6, 'Na data de hoje a equipe focou na área do teto dos vestiários finalizando assim a pintura do masculino e feminino, além disso foi instalado o forro de PVC do Hall de entrada.', '[{"eap": "18.15", "descricao": "APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "18.16", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "19.15", "descricao": "APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "19.16", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "21.11", "descricao": "FORRO DE PVC, LISO, PARA AMBIENTES COMERCIAIS, INCLUSIVE ESTRUTURA DE FIXAÇÃO. AF_05/2017_", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Caio Vinícius Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Cauan Eduardo Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}]'::jsonb),
  ('00353', '2026-03-19', 'NP', 6, 'Na data de hoje a equipe de realizou a finalização da aplicação de selador e pintura do forro do vestiário barreira/ box trocador e sanitário funcionários', '[{"eap": "22.15", "descricao": "APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "22.16", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "24.16", "descricao": "APLICAÇÃO DE FUNDO SELADOR ACRÍLICO EM TETO, UMA DEMÃO. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "24.17", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM TETO, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Caio Vinícius Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Cauan Eduardo Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}]'::jsonb),
  ('00354', '2026-03-20', 'NP', 7, 'Na data de hoje a equipe finalizou a aplicação de pintura em teto da área do laboratório Hoje também foi realizado a impermeabilização do piso para aplicação do vinílico.', '[{"eap": "25.12", "descricao": "APLICAÇÃO MANUAL DE PINTURA COM TINTA LÁTEX ACRÍLICA EM PAREDES, DUAS DEMÃOS. AF_06/2014", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "25.7", "descricao": "PISO VINÍLICO EM MANTA HOMOGÊNEO EM MANTA ESPESSURA 2MM - VER ESPECIFICAÇÕES", "unidade": "%", "qtde_dia": 0, "pct_dia": 0.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Caio Vinícius Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Cauan Eduardo Martins do Amaral"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Aplicador", "nome": "Sebastião Cardoso Sales"}]'::jsonb),
  ('00355', '2026-03-21', 'NP', 2, 'Na data e hoje foi realizado a aplicação da argamassa autonivelante para aplicação posterior do piso vinílico', '[{"eap": "25.7", "descricao": "PISO VINÍLICO EM MANTA HOMOGÊNEO EM MANTA ESPESSURA 2MM - VER ESPECIFICAÇÕES", "unidade": "%", "qtde_dia": 0, "pct_dia": 0.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Aplicador", "nome": "Sebastião Cardoso Sales"}]'::jsonb),
  ('00357', '2026-03-23', 'NP', 5, 'Na data de hoje a equipe deu início na aplicação e piso nas câmaras e antecâmaras da câmara fria, na data de hoje também foi dado início na aplicação do piso vinílico com os rodapés.', '[{"eap": "25.7", "descricao": "PISO VINÍLICO EM MANTA HOMOGÊNEO EM MANTA ESPESSURA 2MM - VER ESPECIFICAÇÕES", "unidade": "%", "qtde_dia": 50, "pct_dia": 0.5, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "25.8", "descricao": "RODAPÉ EM ALUMÍNIO FIXADO NA PAREDE - VER ESPECIFICAÇÕES", "unidade": "%", "qtde_dia": 50, "pct_dia": 0.5, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.4", "descricao": "LASTRO COM MATERIAL GRANULAR, APLICADO EM PISOS OU LAJES SOBRE SOLO, ESPESSURA DE *5 CM*. ", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Aplicador", "nome": "Sebastião Cardoso Sales"}]'::jsonb),
  ('00358', '2026-03-24', 'NP', 6, 'Hoje a equipe finalizou a instalação do piso vinílico do laboratório, hoje também foi dado início no piso da câmara de produtos acabados e antecâmara 2.', '[{"eap": "25.7", "descricao": "PISO VINÍLICO EM MANTA HOMOGÊNEO EM MANTA ESPESSURA 2MM - VER ESPECIFICAÇÕES", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "25.8", "descricao": "RODAPÉ EM ALUMÍNIO FIXADO NA PAREDE - VER ESPECIFICAÇÕES", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.5", "descricao": "PISO EM CONCRETO 20 MPA PREPARO MECÂNICO, ESPESSURA 7CM. AF_09/2020", "unidade": "%", "qtde_dia": 50, "pct_dia": 0.5, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}, {"ocupacao": "Aplicador", "nome": "Sebastião Cardoso Sales"}]'::jsonb),
  ('00359', '2026-03-25', 'NP', 5, 'Na data de hoje a equipe realizou a aplicação do piso na câmara de quarentena e antecâmara 1 finalizando assim a a aplicação do piso nas áreas internas da câmara fria  A equipe alumicon deu sequência na instalação das portas metálicas e realizou a instalação das portas de vidro dos vestiários.', '[{"eap": "26.5", "descricao": "PISO EM CONCRETO 20 MPA PREPARO MECÂNICO, ESPESSURA 7CM. AF_09/2020", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "28.5", "descricao": "PORTA DE VIDRO TRANSPARENTE ABRIR 1 FOLHA", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "28.10", "descricao": "PORTA DE FERRO COMPACTA EM CHAPA, INCLUS. BATENTES E FERRAGENS", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "28.14", "descricao": "PORTA DE FERRO COMPACTA EM CHAPA, INCLUS. BATENTES E FERRAGENS", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}]'::jsonb),
  ('00360', '2026-03-26', 'NP', 5, 'Na data de hoje a equipe realizou a confecção de duas porteiras de correr do brete A equipe de revestimento cerâmico iniciou a aplicação na área interna da câmara de produtos acabados.', '[{"eap": "28.11", "descricao": "PORTA DE CORRER - TIPO MEXICANA - MADEIRA DE LEI MACIÇA", "unidade": "%", "qtde_dia": 20, "pct_dia": 0.2, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.6", "descricao": "ARGAMASSA TRAÇO 1:3 (EM VOLUME DE CIMENTO E AREIA MÉDIA ÚMIDA) COM ADIÇÃO DE IMPERMEABILIZ", "unidade": "%", "qtde_dia": 20, "pct_dia": 0.2, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.7", "descricao": "REVESTIMENTO CERÂMICO PARA PISO COM PLACAS TIPO PORCELANATO DE DIMENSÕES 60X60 CM APLICADA", "unidade": "%", "qtde_dia": 20, "pct_dia": 0.2, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}]'::jsonb),
  ('00361', '2026-03-27', 'NP', 5, 'Na data de hoje a equipe realizou a confecção de mais duas porteiras de correr do brete dos fundos do laboratório A equipe de revestimento cerâmico deu sequência na aplicação na área interna da câmara de produtos acabados.', '[{"eap": "28.11", "descricao": "PORTA DE CORRER - TIPO MEXICANA - MADEIRA DE LEI MACIÇA", "unidade": "%", "qtde_dia": 40, "pct_dia": 0.4, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.6", "descricao": "ARGAMASSA TRAÇO 1:3 (EM VOLUME DE CIMENTO E AREIA MÉDIA ÚMIDA) COM ADIÇÃO DE IMPERMEABILIZ", "unidade": "%", "qtde_dia": 40, "pct_dia": 0.4, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.7", "descricao": "REVESTIMENTO CERÂMICO PARA PISO COM PLACAS TIPO PORCELANATO DE DIMENSÕES 60X60 CM APLICADA", "unidade": "%", "qtde_dia": 40, "pct_dia": 0.4, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}]'::jsonb),
  ('00362', '2026-03-28', 'NP', 5, 'Na data de hoje a equipe de revestimento realizou a aplicação do mesmo na área da antecâmara 2, foi realizado também a adequação de três caixas de passagem.', '[{"eap": "26.6", "descricao": "ARGAMASSA TRAÇO 1:3 (EM VOLUME DE CIMENTO E AREIA MÉDIA ÚMIDA) COM ADIÇÃO DE IMPERMEABILIZ", "unidade": "%", "qtde_dia": 60, "pct_dia": 0.6, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.7", "descricao": "REVESTIMENTO CERÂMICO PARA PISO COM PLACAS TIPO PORCELANATO DE DIMENSÕES 60X60 CM APLICADA", "unidade": "%", "qtde_dia": 60, "pct_dia": 0.6, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "29.2.1", "descricao": "CAIXA DE INSPEÇÃO 80X80CM, PROFUNDIDADE=110CM, TAMPA EM CONCRETO ARMADO COM CANTONEIRAS E=", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}]'::jsonb),
  ('00364', '2026-03-30', 'NP', 6, 'Na data de hoje a equipe de revestimento realizou a aplicação do mesmo na área da câmara de quarentena, a equipe de elétrica realizou também a instalação do rack aéreo na sala do Rack', '[{"eap": "26.6", "descricao": "ARGAMASSA TRAÇO 1:3 (EM VOLUME DE CIMENTO E AREIA MÉDIA ÚMIDA) COM ADIÇÃO DE IMPERMEABILIZ", "unidade": "%", "qtde_dia": 80, "pct_dia": 0.8, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.7", "descricao": "REVESTIMENTO CERÂMICO PARA PISO COM PLACAS TIPO PORCELANATO DE DIMENSÕES 60X60 CM APLICADA", "unidade": "%", "qtde_dia": 80, "pct_dia": 0.8, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "30.4", "descricao": "RACK DE PAREDE 6U, 19\" 450MM - FORNEC. E INST.", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}, {"ocupacao": "Eletricista", "nome": "Geraldo dos Santos"}]'::jsonb),
  ('00365', '2026-03-31', 'NP', 7, 'Na data de hoje a equipe finalizou a aplicação do revestimento de piso na área interna da câmara fria Equipe de refrigeração deu sequência nas conexões para ajustes na refrigeração.', '[{"eap": "26.6", "descricao": "ARGAMASSA TRAÇO 1:3 (EM VOLUME DE CIMENTO E AREIA MÉDIA ÚMIDA) COM ADIÇÃO DE IMPERMEABILIZ", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "26.7", "descricao": "REVESTIMENTO CERÂMICO PARA PISO COM PLACAS TIPO PORCELANATO DE DIMENSÕES 60X60 CM APLICADA", "unidade": "%", "qtde_dia": 100, "pct_dia": 1.0, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "34.1", "descricao": "CÂMARA FRIGORÍFICA PARA RESFRIADOS", "unidade": "%", "qtde_dia": 92, "pct_dia": 0.92, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Pintor", "nome": "Gelson Martins do Amaral"}, {"ocupacao": "Meio-Oficial", "nome": "Carlos Henrique Pereira"}, {"ocupacao": "Refrigeração", "nome": "Thiago da Silva"}, {"ocupacao": "Refrigeração", "nome": "Gabriel do Nascimento"}]'::jsonb),
  ('00366', '2026-04-01', 'NP', 8, 'Hoje demos início na instalação dos equipamentos de climatização posicionando a condensadora que ira filtrar o ar do laboratório em cima da marquise.  A equipe de refrigeração deu sequência nas conexões para ajustes na refrigeração.', '[{"eap": "34.1", "descricao": "CÂMARA FRIGORÍFICA PARA RESFRIADOS", "unidade": "%", "qtde_dia": 94, "pct_dia": 0.94, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.1", "descricao": "AR CONDICIONADO SPLIT INVERTER, HI-WALL (PAREDE), 18000 BTU/H, CICLO FRIO - FORNECIMENTO E", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.2", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - TIPO HI-WALL - 18.000BTU/H", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.3", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.4", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 171.000 BTU/H (15 TRTR)", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.5", "descricao": "KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A22T", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.7", "descricao": "KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A33T", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.12", "descricao": "FANCOLETE HOSPITALAR", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.38", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)", "unidade": "%", "qtde_dia": 5, "pct_dia": 0.05, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Refrigeração", "nome": "Thiago da Silva"}, {"ocupacao": "Refrigeração", "nome": "Gabriel do Nascimento"}, {"ocupacao": "Climatização", "nome": "Higor Guedes"}, {"ocupacao": "Climatização", "nome": "Ícaro Motta"}, {"ocupacao": "Climatização", "nome": "José Ricardo Santos"}]'::jsonb),
  ('00367', '2026-04-02', 'NP', 8, 'Hoje a equipe de climatização deu sequência no posicionamento dos equipamentos na área dos fundos da obra, também   posicionando o equipamento de refrigeração de dentro do Rack . A equipe de refrigeração deu sequência nas conexões para ajustes na refrigeração.', '[{"eap": "34.1", "descricao": "CÂMARA FRIGORÍFICA PARA RESFRIADOS", "unidade": "%", "qtde_dia": 96, "pct_dia": 0.96, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.1", "descricao": "AR CONDICIONADO SPLIT INVERTER, HI-WALL (PAREDE), 18000 BTU/H, CICLO FRIO - FORNECIMENTO E", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.2", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - TIPO HI-WALL - 18.000BTU/H", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.3", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.4", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 171.000 BTU/H (15 TRTR)", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.5", "descricao": "KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A22T", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.7", "descricao": "KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A33T", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.12", "descricao": "FANCOLETE HOSPITALAR", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.38", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)", "unidade": "%", "qtde_dia": 10, "pct_dia": 0.1, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Refrigeração", "nome": "Thiago da Silva"}, {"ocupacao": "Refrigeração", "nome": "Gabriel do Nascimento"}, {"ocupacao": "Climatização", "nome": "Higor Guedes"}, {"ocupacao": "Climatização", "nome": "Ícaro Motta"}, {"ocupacao": "Climatização", "nome": "José Ricardo Santos"}]'::jsonb),
  ('00368', '2026-04-03', 'NP', 8, 'Hoje a equipe de climatização deu sequência nas atividades realizando a instalação das grelhas para filtragem do ar nas salas . A equipe de refrigeração deu sequência nas conexões para ajustes para o resfriamento da Câmara fria.', '[{"eap": "34.1", "descricao": "CÂMARA FRIGORÍFICA PARA RESFRIADOS", "unidade": "%", "qtde_dia": 98, "pct_dia": 0.98, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.1", "descricao": "AR CONDICIONADO SPLIT INVERTER, HI-WALL (PAREDE), 18000 BTU/H, CICLO FRIO - FORNECIMENTO E", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.2", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - TIPO HI-WALL - 18.000BTU/H", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.3", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.4", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 171.000 BTU/H (15 TRTR)", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.5", "descricao": "KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A22T", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.7", "descricao": "KIT REFINET PARA CONEXÃO DE UNIDADES INTERNAS MARCA DAIKIN, MODELO KHRP26A33T", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.12", "descricao": "FANCOLETE HOSPITALAR", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}, {"eap": "33.38", "descricao": "UNIDADE EVAPORADORA - CONDENSADORA - CICLO QUENTE/FRIO 76.600 BTU/H (7,5TR)", "unidade": "%", "qtde_dia": 15, "pct_dia": 0.15, "pct_acum": null, "medicao": 0, "funcionarios": []}]'::jsonb, '[{"ocupacao": "Coordenador de Obras", "nome": "Vilmar dos Santos"}, {"ocupacao": "Ajudante", "nome": "Marcos Silva"}, {"ocupacao": "Meio-Oficial", "nome": "Manoel Alejandro"}, {"ocupacao": "Refrigeração", "nome": "Thiago da Silva"}, {"ocupacao": "Refrigeração", "nome": "Gabriel do Nascimento"}, {"ocupacao": "Climatização", "nome": "Higor Guedes"}, {"ocupacao": "Climatização", "nome": "Ícaro Motta"}, {"ocupacao": "Climatização", "nome": "José Ricardo Santos"}]'::jsonb)
) as t(numero, data, clima, efetivo, comentarios, atividades, equipe);
